# Configuração global - estas variáveis são compartilhadas entre todos os arquivos .rest
@base = http://localhost:3000
@token =Bearer {{authLogin.response.body.accessToken}}

###Auth Login
# @name authLogin
POST {{base}}/auths/login
Content-Type: application/json

{
  "email": "john.doe.hii@example.com",
  "password": "123456"
}  

###Create User
# @name createUser
POST {{base}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "123456"
}

###update user
# @name updateUser
PATCH {{base}}/users/me
Authorization: {{token}}
Content-Type: application/json

{
  "name": "John Doe Hii",
  "email": "john.doe.hii@example.com"
}

###Update Password
# @name updatePassword
PATCH {{base}}/users/me/password
Authorization: {{token}}
Content-Type: application/json  

{
  "currentPassword": "123456789",
  "newPassword": "123456"
}

###Get User By Id
# @name getUserById
GET {{base}}/users/32729982-1022-4cc1-9d17-98d9a1314090
Content-Type: application/json
Authorization: {{token}}
